/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PhysioRouteImport } from './routes/physio'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhysioIndexRouteImport } from './routes/physio.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as PhysioInvitesRouteImport } from './routes/physio.invites'
import { Route as CoachMeRouteImport } from './routes/coach.me'
import { Route as CoachInvitesRouteImport } from './routes/coach.invites'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as PhysioPatientsPatientIdRouteImport } from './routes/physio.patients.$patientId'
import { Route as PatientSessionsSessionIdRouteImport } from './routes/patient.sessions.$sessionId'
import { Route as CoachAthletesAthleteIdRouteImport } from './routes/coach.athletes.$athleteId'
import { Route as CoachAthletesAthleteIdCyclesRouteImport } from './routes/coach.athletes.$athleteId.cycles'
import { Route as CoachAthletesAthleteIdAnalyticsRouteImport } from './routes/coach.athletes.$athleteId.analytics'
import { Route as PhysioPatientsPatientIdSessionsSessionIdRouteImport } from './routes/physio.patients.$patientId.sessions.$sessionId'
import { Route as CoachAthletesAthleteIdCyclesCycleIdRouteImport } from './routes/coach.athletes.$athleteId.cycles.$cycleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioRoute = PhysioRouteImport.update({
  id: '/physio',
  path: '/physio',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioIndexRoute = PhysioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const PhysioInvitesRoute = PhysioInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PhysioRoute,
} as any)
const CoachMeRoute = CoachMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => CoachRoute,
} as any)
const CoachInvitesRoute = CoachInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const PhysioPatientsPatientIdRoute = PhysioPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientSessionsSessionIdRoute =
  PatientSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => PatientRoute,
  } as any)
const CoachAthletesAthleteIdRoute = CoachAthletesAthleteIdRouteImport.update({
  id: '/athletes/$athleteId',
  path: '/athletes/$athleteId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAthletesAthleteIdCyclesRoute =
  CoachAthletesAthleteIdCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const CoachAthletesAthleteIdAnalyticsRoute =
  CoachAthletesAthleteIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const PhysioPatientsPatientIdSessionsSessionIdRoute =
  PhysioPatientsPatientIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => PhysioPatientsPatientIdRoute,
  } as any)
const CoachAthletesAthleteIdCyclesCycleIdRoute =
  CoachAthletesAthleteIdCyclesCycleIdRouteImport.update({
    id: '/$cycleId',
    path: '/$cycleId',
    getParentRoute: () => CoachAthletesAthleteIdCyclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRouteWithChildren
  '/physio': typeof PhysioRouteWithChildren
  '/signup': typeof SignupRoute
  '/history': typeof AppHistoryRoute
  '/me': typeof AppMeRoute
  '/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/me': typeof CoachMeRoute
  '/physio/invites': typeof PhysioInvitesRoute
  '/coach/': typeof CoachIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physio/': typeof PhysioIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRouteWithChildren
  '/patient/sessions/$sessionId': typeof PatientSessionsSessionIdRoute
  '/physio/patients/$patientId': typeof PhysioPatientsPatientIdRouteWithChildren
  '/coach/athletes/$athleteId/analytics': typeof CoachAthletesAthleteIdAnalyticsRoute
  '/coach/athletes/$athleteId/cycles': typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  '/coach/athletes/$athleteId/cycles/$cycleId': typeof CoachAthletesAthleteIdCyclesCycleIdRoute
  '/physio/patients/$patientId/sessions/$sessionId': typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/history': typeof AppHistoryRoute
  '/me': typeof AppMeRoute
  '/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/me': typeof CoachMeRoute
  '/physio/invites': typeof PhysioInvitesRoute
  '/coach': typeof CoachIndexRoute
  '/patient': typeof PatientIndexRoute
  '/physio': typeof PhysioIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRouteWithChildren
  '/patient/sessions/$sessionId': typeof PatientSessionsSessionIdRoute
  '/physio/patients/$patientId': typeof PhysioPatientsPatientIdRouteWithChildren
  '/coach/athletes/$athleteId/analytics': typeof CoachAthletesAthleteIdAnalyticsRoute
  '/coach/athletes/$athleteId/cycles': typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  '/coach/athletes/$athleteId/cycles/$cycleId': typeof CoachAthletesAthleteIdCyclesCycleIdRoute
  '/physio/patients/$patientId/sessions/$sessionId': typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRouteWithChildren
  '/physio': typeof PhysioRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/me': typeof AppMeRoute
  '/_app/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/me': typeof CoachMeRoute
  '/physio/invites': typeof PhysioInvitesRoute
  '/coach/': typeof CoachIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physio/': typeof PhysioIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRouteWithChildren
  '/patient/sessions/$sessionId': typeof PatientSessionsSessionIdRoute
  '/physio/patients/$patientId': typeof PhysioPatientsPatientIdRouteWithChildren
  '/coach/athletes/$athleteId/analytics': typeof CoachAthletesAthleteIdAnalyticsRoute
  '/coach/athletes/$athleteId/cycles': typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  '/coach/athletes/$athleteId/cycles/$cycleId': typeof CoachAthletesAthleteIdCyclesCycleIdRoute
  '/physio/patients/$patientId/sessions/$sessionId': typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/patient'
    | '/physio'
    | '/signup'
    | '/history'
    | '/me'
    | '/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/me'
    | '/physio/invites'
    | '/coach/'
    | '/patient/'
    | '/physio/'
    | '/coach/athletes/$athleteId'
    | '/patient/sessions/$sessionId'
    | '/physio/patients/$patientId'
    | '/coach/athletes/$athleteId/analytics'
    | '/coach/athletes/$athleteId/cycles'
    | '/coach/athletes/$athleteId/cycles/$cycleId'
    | '/physio/patients/$patientId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/signup'
    | '/history'
    | '/me'
    | '/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/me'
    | '/physio/invites'
    | '/coach'
    | '/patient'
    | '/physio'
    | '/coach/athletes/$athleteId'
    | '/patient/sessions/$sessionId'
    | '/physio/patients/$patientId'
    | '/coach/athletes/$athleteId/analytics'
    | '/coach/athletes/$athleteId/cycles'
    | '/coach/athletes/$athleteId/cycles/$cycleId'
    | '/physio/patients/$patientId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/coach'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/patient'
    | '/physio'
    | '/signup'
    | '/_app/history'
    | '/_app/me'
    | '/_app/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/me'
    | '/physio/invites'
    | '/coach/'
    | '/patient/'
    | '/physio/'
    | '/coach/athletes/$athleteId'
    | '/patient/sessions/$sessionId'
    | '/physio/patients/$patientId'
    | '/coach/athletes/$athleteId/analytics'
    | '/coach/athletes/$athleteId/cycles'
    | '/coach/athletes/$athleteId/cycles/$cycleId'
    | '/physio/patients/$patientId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  PatientRoute: typeof PatientRouteWithChildren
  PhysioRoute: typeof PhysioRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio': {
      id: '/physio'
      path: '/physio'
      fullPath: '/physio'
      preLoaderRoute: typeof PhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/': {
      id: '/physio/'
      path: '/'
      fullPath: '/physio/'
      preLoaderRoute: typeof PhysioIndexRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/physio/invites': {
      id: '/physio/invites'
      path: '/invites'
      fullPath: '/physio/invites'
      preLoaderRoute: typeof PhysioInvitesRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/coach/me': {
      id: '/coach/me'
      path: '/me'
      fullPath: '/coach/me'
      preLoaderRoute: typeof CoachMeRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/invites': {
      id: '/coach/invites'
      path: '/invites'
      fullPath: '/coach/invites'
      preLoaderRoute: typeof CoachInvitesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/physio/patients/$patientId': {
      id: '/physio/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/physio/patients/$patientId'
      preLoaderRoute: typeof PhysioPatientsPatientIdRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/sessions/$sessionId': {
      id: '/patient/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/patient/sessions/$sessionId'
      preLoaderRoute: typeof PatientSessionsSessionIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/coach/athletes/$athleteId': {
      id: '/coach/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/coach/athletes/$athleteId'
      preLoaderRoute: typeof CoachAthletesAthleteIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/athletes/$athleteId/cycles': {
      id: '/coach/athletes/$athleteId/cycles'
      path: '/cycles'
      fullPath: '/coach/athletes/$athleteId/cycles'
      preLoaderRoute: typeof CoachAthletesAthleteIdCyclesRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/coach/athletes/$athleteId/analytics': {
      id: '/coach/athletes/$athleteId/analytics'
      path: '/analytics'
      fullPath: '/coach/athletes/$athleteId/analytics'
      preLoaderRoute: typeof CoachAthletesAthleteIdAnalyticsRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/physio/patients/$patientId/sessions/$sessionId': {
      id: '/physio/patients/$patientId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/physio/patients/$patientId/sessions/$sessionId'
      preLoaderRoute: typeof PhysioPatientsPatientIdSessionsSessionIdRouteImport
      parentRoute: typeof PhysioPatientsPatientIdRoute
    }
    '/coach/athletes/$athleteId/cycles/$cycleId': {
      id: '/coach/athletes/$athleteId/cycles/$cycleId'
      path: '/$cycleId'
      fullPath: '/coach/athletes/$athleteId/cycles/$cycleId'
      preLoaderRoute: typeof CoachAthletesAthleteIdCyclesCycleIdRouteImport
      parentRoute: typeof CoachAthletesAthleteIdCyclesRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppMeRoute: typeof AppMeRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppMeRoute: AppMeRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachAthletesAthleteIdCyclesRouteChildren {
  CoachAthletesAthleteIdCyclesCycleIdRoute: typeof CoachAthletesAthleteIdCyclesCycleIdRoute
}

const CoachAthletesAthleteIdCyclesRouteChildren: CoachAthletesAthleteIdCyclesRouteChildren =
  {
    CoachAthletesAthleteIdCyclesCycleIdRoute:
      CoachAthletesAthleteIdCyclesCycleIdRoute,
  }

const CoachAthletesAthleteIdCyclesRouteWithChildren =
  CoachAthletesAthleteIdCyclesRoute._addFileChildren(
    CoachAthletesAthleteIdCyclesRouteChildren,
  )

interface CoachAthletesAthleteIdRouteChildren {
  CoachAthletesAthleteIdAnalyticsRoute: typeof CoachAthletesAthleteIdAnalyticsRoute
  CoachAthletesAthleteIdCyclesRoute: typeof CoachAthletesAthleteIdCyclesRouteWithChildren
}

const CoachAthletesAthleteIdRouteChildren: CoachAthletesAthleteIdRouteChildren =
  {
    CoachAthletesAthleteIdAnalyticsRoute: CoachAthletesAthleteIdAnalyticsRoute,
    CoachAthletesAthleteIdCyclesRoute:
      CoachAthletesAthleteIdCyclesRouteWithChildren,
  }

const CoachAthletesAthleteIdRouteWithChildren =
  CoachAthletesAthleteIdRoute._addFileChildren(
    CoachAthletesAthleteIdRouteChildren,
  )

interface CoachRouteChildren {
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachInvitesRoute: typeof CoachInvitesRoute
  CoachMeRoute: typeof CoachMeRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAthletesAthleteIdRoute: typeof CoachAthletesAthleteIdRouteWithChildren
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachExercisesRoute: CoachExercisesRoute,
  CoachInvitesRoute: CoachInvitesRoute,
  CoachMeRoute: CoachMeRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachAthletesAthleteIdRoute: CoachAthletesAthleteIdRouteWithChildren,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface PatientRouteChildren {
  PatientIndexRoute: typeof PatientIndexRoute
  PatientSessionsSessionIdRoute: typeof PatientSessionsSessionIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientIndexRoute: PatientIndexRoute,
  PatientSessionsSessionIdRoute: PatientSessionsSessionIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PhysioPatientsPatientIdRouteChildren {
  PhysioPatientsPatientIdSessionsSessionIdRoute: typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}

const PhysioPatientsPatientIdRouteChildren: PhysioPatientsPatientIdRouteChildren =
  {
    PhysioPatientsPatientIdSessionsSessionIdRoute:
      PhysioPatientsPatientIdSessionsSessionIdRoute,
  }

const PhysioPatientsPatientIdRouteWithChildren =
  PhysioPatientsPatientIdRoute._addFileChildren(
    PhysioPatientsPatientIdRouteChildren,
  )

interface PhysioRouteChildren {
  PhysioInvitesRoute: typeof PhysioInvitesRoute
  PhysioIndexRoute: typeof PhysioIndexRoute
  PhysioPatientsPatientIdRoute: typeof PhysioPatientsPatientIdRouteWithChildren
}

const PhysioRouteChildren: PhysioRouteChildren = {
  PhysioInvitesRoute: PhysioInvitesRoute,
  PhysioIndexRoute: PhysioIndexRoute,
  PhysioPatientsPatientIdRoute: PhysioPatientsPatientIdRouteWithChildren,
}

const PhysioRouteWithChildren =
  PhysioRoute._addFileChildren(PhysioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  PatientRoute: PatientRouteWithChildren,
  PhysioRoute: PhysioRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
