/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachTemplatesRouteImport } from './routes/coach.templates'
import { Route as CoachInvitesRouteImport } from './routes/coach.invites'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as CoachAthletesAthleteIdRouteImport } from './routes/coach.athletes.$athleteId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachTemplatesRoute = CoachTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => CoachRoute,
} as any)
const CoachInvitesRoute = CoachInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const CoachAthletesAthleteIdRoute = CoachAthletesAthleteIdRouteImport.update({
  id: '/athletes/$athleteId',
  path: '/athletes/$athleteId',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/history': typeof AppHistoryRoute
  '/me': typeof AppMeRoute
  '/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/templates': typeof CoachTemplatesRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/history': typeof AppHistoryRoute
  '/me': typeof AppMeRoute
  '/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/templates': typeof CoachTemplatesRoute
  '/coach': typeof CoachIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/me': typeof AppMeRoute
  '/_app/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/templates': typeof CoachTemplatesRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/login'
    | '/signup'
    | '/history'
    | '/me'
    | '/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/templates'
    | '/coach/'
    | '/coach/athletes/$athleteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/history'
    | '/me'
    | '/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/templates'
    | '/coach'
    | '/coach/athletes/$athleteId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/coach'
    | '/login'
    | '/signup'
    | '/_app/history'
    | '/_app/me'
    | '/_app/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/templates'
    | '/coach/'
    | '/coach/athletes/$athleteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/templates': {
      id: '/coach/templates'
      path: '/templates'
      fullPath: '/coach/templates'
      preLoaderRoute: typeof CoachTemplatesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/invites': {
      id: '/coach/invites'
      path: '/invites'
      fullPath: '/coach/invites'
      preLoaderRoute: typeof CoachInvitesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/coach/athletes/$athleteId': {
      id: '/coach/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/coach/athletes/$athleteId'
      preLoaderRoute: typeof CoachAthletesAthleteIdRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppMeRoute: typeof AppMeRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppMeRoute: AppMeRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachRouteChildren {
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachInvitesRoute: typeof CoachInvitesRoute
  CoachTemplatesRoute: typeof CoachTemplatesRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAthletesAthleteIdRoute: typeof CoachAthletesAthleteIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachExercisesRoute: CoachExercisesRoute,
  CoachInvitesRoute: CoachInvitesRoute,
  CoachTemplatesRoute: CoachTemplatesRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachAthletesAthleteIdRoute: CoachAthletesAthleteIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
