/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PhysioRouteImport } from './routes/physio'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhysioIndexRouteImport } from './routes/physio.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as PhysioTemplatesRouteImport } from './routes/physio.templates'
import { Route as PhysioMeRouteImport } from './routes/physio.me'
import { Route as PhysioInvitesRouteImport } from './routes/physio.invites'
import { Route as PhysioBandsRouteImport } from './routes/physio.bands'
import { Route as PatientProgressionRouteImport } from './routes/patient.progression'
import { Route as PatientMeRouteImport } from './routes/patient.me'
import { Route as PatientCalendarRouteImport } from './routes/patient.calendar'
import { Route as CoachMethodologyRouteImport } from './routes/coach.methodology'
import { Route as CoachMeRouteImport } from './routes/coach.me'
import { Route as CoachInvitesRouteImport } from './routes/coach.invites'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppEnduranceRouteImport } from './routes/_app.endurance'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as PhysioTemplatesTemplateIdRouteImport } from './routes/physio.templates.$templateId'
import { Route as PhysioPatientsPatientIdRouteImport } from './routes/physio.patients.$patientId'
import { Route as PatientSessionsSessionIdRouteImport } from './routes/patient.sessions.$sessionId'
import { Route as CoachAthletesAthleteIdRouteImport } from './routes/coach.athletes.$athleteId'
import { Route as PhysioPatientsPatientIdProgressionRouteImport } from './routes/physio.patients.$patientId.progression'
import { Route as PhysioPatientsPatientIdCalendarRouteImport } from './routes/physio.patients.$patientId.calendar'
import { Route as CoachAthletesAthleteIdStatsRouteImport } from './routes/coach.athletes.$athleteId.stats'
import { Route as CoachAthletesAthleteIdEnduranceRouteImport } from './routes/coach.athletes.$athleteId.endurance'
import { Route as CoachAthletesAthleteIdCyclesRouteImport } from './routes/coach.athletes.$athleteId.cycles'
import { Route as CoachAthletesAthleteIdCalendarRouteImport } from './routes/coach.athletes.$athleteId.calendar'
import { Route as CoachAthletesAthleteIdAnalyticsRouteImport } from './routes/coach.athletes.$athleteId.analytics'
import { Route as PhysioPatientsPatientIdSessionsSessionIdRouteImport } from './routes/physio.patients.$patientId.sessions.$sessionId'
import { Route as PhysioPatientsPatientIdPlansPlanIdRouteImport } from './routes/physio.patients.$patientId.plans.$planId'
import { Route as CoachAthletesAthleteIdCyclesCycleIdRouteImport } from './routes/coach.athletes.$athleteId.cycles.$cycleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioRoute = PhysioRouteImport.update({
  id: '/physio',
  path: '/physio',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioIndexRoute = PhysioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const PhysioTemplatesRoute = PhysioTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioMeRoute = PhysioMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioInvitesRoute = PhysioInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioBandsRoute = PhysioBandsRouteImport.update({
  id: '/bands',
  path: '/bands',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientProgressionRoute = PatientProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMeRoute = PatientMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCalendarRoute = PatientCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PatientRoute,
} as any)
const CoachMethodologyRoute = CoachMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => CoachRoute,
} as any)
const CoachMeRoute = CoachMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => CoachRoute,
} as any)
const CoachInvitesRoute = CoachInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEnduranceRoute = AppEnduranceRouteImport.update({
  id: '/endurance',
  path: '/endurance',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const PhysioTemplatesTemplateIdRoute =
  PhysioTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => PhysioTemplatesRoute,
  } as any)
const PhysioPatientsPatientIdRoute = PhysioPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientSessionsSessionIdRoute =
  PatientSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => PatientRoute,
  } as any)
const CoachAthletesAthleteIdRoute = CoachAthletesAthleteIdRouteImport.update({
  id: '/athletes/$athleteId',
  path: '/athletes/$athleteId',
  getParentRoute: () => CoachRoute,
} as any)
const PhysioPatientsPatientIdProgressionRoute =
  PhysioPatientsPatientIdProgressionRouteImport.update({
    id: '/progression',
    path: '/progression',
    getParentRoute: () => PhysioPatientsPatientIdRoute,
  } as any)
const PhysioPatientsPatientIdCalendarRoute =
  PhysioPatientsPatientIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => PhysioPatientsPatientIdRoute,
  } as any)
const CoachAthletesAthleteIdStatsRoute =
  CoachAthletesAthleteIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const CoachAthletesAthleteIdEnduranceRoute =
  CoachAthletesAthleteIdEnduranceRouteImport.update({
    id: '/endurance',
    path: '/endurance',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const CoachAthletesAthleteIdCyclesRoute =
  CoachAthletesAthleteIdCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const CoachAthletesAthleteIdCalendarRoute =
  CoachAthletesAthleteIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const CoachAthletesAthleteIdAnalyticsRoute =
  CoachAthletesAthleteIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => CoachAthletesAthleteIdRoute,
  } as any)
const PhysioPatientsPatientIdSessionsSessionIdRoute =
  PhysioPatientsPatientIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => PhysioPatientsPatientIdRoute,
  } as any)
const PhysioPatientsPatientIdPlansPlanIdRoute =
  PhysioPatientsPatientIdPlansPlanIdRouteImport.update({
    id: '/plans/$planId',
    path: '/plans/$planId',
    getParentRoute: () => PhysioPatientsPatientIdRoute,
  } as any)
const CoachAthletesAthleteIdCyclesCycleIdRoute =
  CoachAthletesAthleteIdCyclesCycleIdRouteImport.update({
    id: '/$cycleId',
    path: '/$cycleId',
    getParentRoute: () => CoachAthletesAthleteIdCyclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRouteWithChildren
  '/physio': typeof PhysioRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AppCalendarRoute
  '/endurance': typeof AppEnduranceRoute
  '/history': typeof AppHistoryRoute
  '/me': typeof AppMeRoute
  '/stats': typeof AppStatsRoute
  '/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/me': typeof CoachMeRoute
  '/coach/methodology': typeof CoachMethodologyRoute
  '/patient/calendar': typeof PatientCalendarRoute
  '/patient/me': typeof PatientMeRoute
  '/patient/progression': typeof PatientProgressionRoute
  '/physio/bands': typeof PhysioBandsRoute
  '/physio/invites': typeof PhysioInvitesRoute
  '/physio/me': typeof PhysioMeRoute
  '/physio/templates': typeof PhysioTemplatesRouteWithChildren
  '/coach/': typeof CoachIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physio/': typeof PhysioIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRouteWithChildren
  '/patient/sessions/$sessionId': typeof PatientSessionsSessionIdRoute
  '/physio/patients/$patientId': typeof PhysioPatientsPatientIdRouteWithChildren
  '/physio/templates/$templateId': typeof PhysioTemplatesTemplateIdRoute
  '/coach/athletes/$athleteId/analytics': typeof CoachAthletesAthleteIdAnalyticsRoute
  '/coach/athletes/$athleteId/calendar': typeof CoachAthletesAthleteIdCalendarRoute
  '/coach/athletes/$athleteId/cycles': typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  '/coach/athletes/$athleteId/endurance': typeof CoachAthletesAthleteIdEnduranceRoute
  '/coach/athletes/$athleteId/stats': typeof CoachAthletesAthleteIdStatsRoute
  '/physio/patients/$patientId/calendar': typeof PhysioPatientsPatientIdCalendarRoute
  '/physio/patients/$patientId/progression': typeof PhysioPatientsPatientIdProgressionRoute
  '/coach/athletes/$athleteId/cycles/$cycleId': typeof CoachAthletesAthleteIdCyclesCycleIdRoute
  '/physio/patients/$patientId/plans/$planId': typeof PhysioPatientsPatientIdPlansPlanIdRoute
  '/physio/patients/$patientId/sessions/$sessionId': typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AppCalendarRoute
  '/endurance': typeof AppEnduranceRoute
  '/history': typeof AppHistoryRoute
  '/me': typeof AppMeRoute
  '/stats': typeof AppStatsRoute
  '/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/me': typeof CoachMeRoute
  '/coach/methodology': typeof CoachMethodologyRoute
  '/patient/calendar': typeof PatientCalendarRoute
  '/patient/me': typeof PatientMeRoute
  '/patient/progression': typeof PatientProgressionRoute
  '/physio/bands': typeof PhysioBandsRoute
  '/physio/invites': typeof PhysioInvitesRoute
  '/physio/me': typeof PhysioMeRoute
  '/physio/templates': typeof PhysioTemplatesRouteWithChildren
  '/coach': typeof CoachIndexRoute
  '/patient': typeof PatientIndexRoute
  '/physio': typeof PhysioIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRouteWithChildren
  '/patient/sessions/$sessionId': typeof PatientSessionsSessionIdRoute
  '/physio/patients/$patientId': typeof PhysioPatientsPatientIdRouteWithChildren
  '/physio/templates/$templateId': typeof PhysioTemplatesTemplateIdRoute
  '/coach/athletes/$athleteId/analytics': typeof CoachAthletesAthleteIdAnalyticsRoute
  '/coach/athletes/$athleteId/calendar': typeof CoachAthletesAthleteIdCalendarRoute
  '/coach/athletes/$athleteId/cycles': typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  '/coach/athletes/$athleteId/endurance': typeof CoachAthletesAthleteIdEnduranceRoute
  '/coach/athletes/$athleteId/stats': typeof CoachAthletesAthleteIdStatsRoute
  '/physio/patients/$patientId/calendar': typeof PhysioPatientsPatientIdCalendarRoute
  '/physio/patients/$patientId/progression': typeof PhysioPatientsPatientIdProgressionRoute
  '/coach/athletes/$athleteId/cycles/$cycleId': typeof CoachAthletesAthleteIdCyclesCycleIdRoute
  '/physio/patients/$patientId/plans/$planId': typeof PhysioPatientsPatientIdPlansPlanIdRoute
  '/physio/patients/$patientId/sessions/$sessionId': typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/patient': typeof PatientRouteWithChildren
  '/physio': typeof PhysioRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/endurance': typeof AppEnduranceRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/me': typeof AppMeRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/today': typeof AppTodayRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/invites': typeof CoachInvitesRoute
  '/coach/me': typeof CoachMeRoute
  '/coach/methodology': typeof CoachMethodologyRoute
  '/patient/calendar': typeof PatientCalendarRoute
  '/patient/me': typeof PatientMeRoute
  '/patient/progression': typeof PatientProgressionRoute
  '/physio/bands': typeof PhysioBandsRoute
  '/physio/invites': typeof PhysioInvitesRoute
  '/physio/me': typeof PhysioMeRoute
  '/physio/templates': typeof PhysioTemplatesRouteWithChildren
  '/coach/': typeof CoachIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physio/': typeof PhysioIndexRoute
  '/coach/athletes/$athleteId': typeof CoachAthletesAthleteIdRouteWithChildren
  '/patient/sessions/$sessionId': typeof PatientSessionsSessionIdRoute
  '/physio/patients/$patientId': typeof PhysioPatientsPatientIdRouteWithChildren
  '/physio/templates/$templateId': typeof PhysioTemplatesTemplateIdRoute
  '/coach/athletes/$athleteId/analytics': typeof CoachAthletesAthleteIdAnalyticsRoute
  '/coach/athletes/$athleteId/calendar': typeof CoachAthletesAthleteIdCalendarRoute
  '/coach/athletes/$athleteId/cycles': typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  '/coach/athletes/$athleteId/endurance': typeof CoachAthletesAthleteIdEnduranceRoute
  '/coach/athletes/$athleteId/stats': typeof CoachAthletesAthleteIdStatsRoute
  '/physio/patients/$patientId/calendar': typeof PhysioPatientsPatientIdCalendarRoute
  '/physio/patients/$patientId/progression': typeof PhysioPatientsPatientIdProgressionRoute
  '/coach/athletes/$athleteId/cycles/$cycleId': typeof CoachAthletesAthleteIdCyclesCycleIdRoute
  '/physio/patients/$patientId/plans/$planId': typeof PhysioPatientsPatientIdPlansPlanIdRoute
  '/physio/patients/$patientId/sessions/$sessionId': typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/patient'
    | '/physio'
    | '/signup'
    | '/sitemap.xml'
    | '/calendar'
    | '/endurance'
    | '/history'
    | '/me'
    | '/stats'
    | '/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/me'
    | '/coach/methodology'
    | '/patient/calendar'
    | '/patient/me'
    | '/patient/progression'
    | '/physio/bands'
    | '/physio/invites'
    | '/physio/me'
    | '/physio/templates'
    | '/coach/'
    | '/patient/'
    | '/physio/'
    | '/coach/athletes/$athleteId'
    | '/patient/sessions/$sessionId'
    | '/physio/patients/$patientId'
    | '/physio/templates/$templateId'
    | '/coach/athletes/$athleteId/analytics'
    | '/coach/athletes/$athleteId/calendar'
    | '/coach/athletes/$athleteId/cycles'
    | '/coach/athletes/$athleteId/endurance'
    | '/coach/athletes/$athleteId/stats'
    | '/physio/patients/$patientId/calendar'
    | '/physio/patients/$patientId/progression'
    | '/coach/athletes/$athleteId/cycles/$cycleId'
    | '/physio/patients/$patientId/plans/$planId'
    | '/physio/patients/$patientId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/calendar'
    | '/endurance'
    | '/history'
    | '/me'
    | '/stats'
    | '/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/me'
    | '/coach/methodology'
    | '/patient/calendar'
    | '/patient/me'
    | '/patient/progression'
    | '/physio/bands'
    | '/physio/invites'
    | '/physio/me'
    | '/physio/templates'
    | '/coach'
    | '/patient'
    | '/physio'
    | '/coach/athletes/$athleteId'
    | '/patient/sessions/$sessionId'
    | '/physio/patients/$patientId'
    | '/physio/templates/$templateId'
    | '/coach/athletes/$athleteId/analytics'
    | '/coach/athletes/$athleteId/calendar'
    | '/coach/athletes/$athleteId/cycles'
    | '/coach/athletes/$athleteId/endurance'
    | '/coach/athletes/$athleteId/stats'
    | '/physio/patients/$patientId/calendar'
    | '/physio/patients/$patientId/progression'
    | '/coach/athletes/$athleteId/cycles/$cycleId'
    | '/physio/patients/$patientId/plans/$planId'
    | '/physio/patients/$patientId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/coach'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/patient'
    | '/physio'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/calendar'
    | '/_app/endurance'
    | '/_app/history'
    | '/_app/me'
    | '/_app/stats'
    | '/_app/today'
    | '/coach/exercises'
    | '/coach/invites'
    | '/coach/me'
    | '/coach/methodology'
    | '/patient/calendar'
    | '/patient/me'
    | '/patient/progression'
    | '/physio/bands'
    | '/physio/invites'
    | '/physio/me'
    | '/physio/templates'
    | '/coach/'
    | '/patient/'
    | '/physio/'
    | '/coach/athletes/$athleteId'
    | '/patient/sessions/$sessionId'
    | '/physio/patients/$patientId'
    | '/physio/templates/$templateId'
    | '/coach/athletes/$athleteId/analytics'
    | '/coach/athletes/$athleteId/calendar'
    | '/coach/athletes/$athleteId/cycles'
    | '/coach/athletes/$athleteId/endurance'
    | '/coach/athletes/$athleteId/stats'
    | '/physio/patients/$patientId/calendar'
    | '/physio/patients/$patientId/progression'
    | '/coach/athletes/$athleteId/cycles/$cycleId'
    | '/physio/patients/$patientId/plans/$planId'
    | '/physio/patients/$patientId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  PatientRoute: typeof PatientRouteWithChildren
  PhysioRoute: typeof PhysioRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio': {
      id: '/physio'
      path: '/physio'
      fullPath: '/physio'
      preLoaderRoute: typeof PhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/': {
      id: '/physio/'
      path: '/'
      fullPath: '/physio/'
      preLoaderRoute: typeof PhysioIndexRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/physio/templates': {
      id: '/physio/templates'
      path: '/templates'
      fullPath: '/physio/templates'
      preLoaderRoute: typeof PhysioTemplatesRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/me': {
      id: '/physio/me'
      path: '/me'
      fullPath: '/physio/me'
      preLoaderRoute: typeof PhysioMeRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/invites': {
      id: '/physio/invites'
      path: '/invites'
      fullPath: '/physio/invites'
      preLoaderRoute: typeof PhysioInvitesRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/bands': {
      id: '/physio/bands'
      path: '/bands'
      fullPath: '/physio/bands'
      preLoaderRoute: typeof PhysioBandsRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/progression': {
      id: '/patient/progression'
      path: '/progression'
      fullPath: '/patient/progression'
      preLoaderRoute: typeof PatientProgressionRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/me': {
      id: '/patient/me'
      path: '/me'
      fullPath: '/patient/me'
      preLoaderRoute: typeof PatientMeRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/calendar': {
      id: '/patient/calendar'
      path: '/calendar'
      fullPath: '/patient/calendar'
      preLoaderRoute: typeof PatientCalendarRouteImport
      parentRoute: typeof PatientRoute
    }
    '/coach/methodology': {
      id: '/coach/methodology'
      path: '/methodology'
      fullPath: '/coach/methodology'
      preLoaderRoute: typeof CoachMethodologyRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/me': {
      id: '/coach/me'
      path: '/me'
      fullPath: '/coach/me'
      preLoaderRoute: typeof CoachMeRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/invites': {
      id: '/coach/invites'
      path: '/invites'
      fullPath: '/coach/invites'
      preLoaderRoute: typeof CoachInvitesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endurance': {
      id: '/_app/endurance'
      path: '/endurance'
      fullPath: '/endurance'
      preLoaderRoute: typeof AppEnduranceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/physio/templates/$templateId': {
      id: '/physio/templates/$templateId'
      path: '/$templateId'
      fullPath: '/physio/templates/$templateId'
      preLoaderRoute: typeof PhysioTemplatesTemplateIdRouteImport
      parentRoute: typeof PhysioTemplatesRoute
    }
    '/physio/patients/$patientId': {
      id: '/physio/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/physio/patients/$patientId'
      preLoaderRoute: typeof PhysioPatientsPatientIdRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/sessions/$sessionId': {
      id: '/patient/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/patient/sessions/$sessionId'
      preLoaderRoute: typeof PatientSessionsSessionIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/coach/athletes/$athleteId': {
      id: '/coach/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/coach/athletes/$athleteId'
      preLoaderRoute: typeof CoachAthletesAthleteIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/physio/patients/$patientId/progression': {
      id: '/physio/patients/$patientId/progression'
      path: '/progression'
      fullPath: '/physio/patients/$patientId/progression'
      preLoaderRoute: typeof PhysioPatientsPatientIdProgressionRouteImport
      parentRoute: typeof PhysioPatientsPatientIdRoute
    }
    '/physio/patients/$patientId/calendar': {
      id: '/physio/patients/$patientId/calendar'
      path: '/calendar'
      fullPath: '/physio/patients/$patientId/calendar'
      preLoaderRoute: typeof PhysioPatientsPatientIdCalendarRouteImport
      parentRoute: typeof PhysioPatientsPatientIdRoute
    }
    '/coach/athletes/$athleteId/stats': {
      id: '/coach/athletes/$athleteId/stats'
      path: '/stats'
      fullPath: '/coach/athletes/$athleteId/stats'
      preLoaderRoute: typeof CoachAthletesAthleteIdStatsRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/coach/athletes/$athleteId/endurance': {
      id: '/coach/athletes/$athleteId/endurance'
      path: '/endurance'
      fullPath: '/coach/athletes/$athleteId/endurance'
      preLoaderRoute: typeof CoachAthletesAthleteIdEnduranceRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/coach/athletes/$athleteId/cycles': {
      id: '/coach/athletes/$athleteId/cycles'
      path: '/cycles'
      fullPath: '/coach/athletes/$athleteId/cycles'
      preLoaderRoute: typeof CoachAthletesAthleteIdCyclesRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/coach/athletes/$athleteId/calendar': {
      id: '/coach/athletes/$athleteId/calendar'
      path: '/calendar'
      fullPath: '/coach/athletes/$athleteId/calendar'
      preLoaderRoute: typeof CoachAthletesAthleteIdCalendarRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/coach/athletes/$athleteId/analytics': {
      id: '/coach/athletes/$athleteId/analytics'
      path: '/analytics'
      fullPath: '/coach/athletes/$athleteId/analytics'
      preLoaderRoute: typeof CoachAthletesAthleteIdAnalyticsRouteImport
      parentRoute: typeof CoachAthletesAthleteIdRoute
    }
    '/physio/patients/$patientId/sessions/$sessionId': {
      id: '/physio/patients/$patientId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/physio/patients/$patientId/sessions/$sessionId'
      preLoaderRoute: typeof PhysioPatientsPatientIdSessionsSessionIdRouteImport
      parentRoute: typeof PhysioPatientsPatientIdRoute
    }
    '/physio/patients/$patientId/plans/$planId': {
      id: '/physio/patients/$patientId/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/physio/patients/$patientId/plans/$planId'
      preLoaderRoute: typeof PhysioPatientsPatientIdPlansPlanIdRouteImport
      parentRoute: typeof PhysioPatientsPatientIdRoute
    }
    '/coach/athletes/$athleteId/cycles/$cycleId': {
      id: '/coach/athletes/$athleteId/cycles/$cycleId'
      path: '/$cycleId'
      fullPath: '/coach/athletes/$athleteId/cycles/$cycleId'
      preLoaderRoute: typeof CoachAthletesAthleteIdCyclesCycleIdRouteImport
      parentRoute: typeof CoachAthletesAthleteIdCyclesRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppEnduranceRoute: typeof AppEnduranceRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMeRoute: typeof AppMeRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppEnduranceRoute: AppEnduranceRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMeRoute: AppMeRoute,
  AppStatsRoute: AppStatsRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachAthletesAthleteIdCyclesRouteChildren {
  CoachAthletesAthleteIdCyclesCycleIdRoute: typeof CoachAthletesAthleteIdCyclesCycleIdRoute
}

const CoachAthletesAthleteIdCyclesRouteChildren: CoachAthletesAthleteIdCyclesRouteChildren =
  {
    CoachAthletesAthleteIdCyclesCycleIdRoute:
      CoachAthletesAthleteIdCyclesCycleIdRoute,
  }

const CoachAthletesAthleteIdCyclesRouteWithChildren =
  CoachAthletesAthleteIdCyclesRoute._addFileChildren(
    CoachAthletesAthleteIdCyclesRouteChildren,
  )

interface CoachAthletesAthleteIdRouteChildren {
  CoachAthletesAthleteIdAnalyticsRoute: typeof CoachAthletesAthleteIdAnalyticsRoute
  CoachAthletesAthleteIdCalendarRoute: typeof CoachAthletesAthleteIdCalendarRoute
  CoachAthletesAthleteIdCyclesRoute: typeof CoachAthletesAthleteIdCyclesRouteWithChildren
  CoachAthletesAthleteIdEnduranceRoute: typeof CoachAthletesAthleteIdEnduranceRoute
  CoachAthletesAthleteIdStatsRoute: typeof CoachAthletesAthleteIdStatsRoute
}

const CoachAthletesAthleteIdRouteChildren: CoachAthletesAthleteIdRouteChildren =
  {
    CoachAthletesAthleteIdAnalyticsRoute: CoachAthletesAthleteIdAnalyticsRoute,
    CoachAthletesAthleteIdCalendarRoute: CoachAthletesAthleteIdCalendarRoute,
    CoachAthletesAthleteIdCyclesRoute:
      CoachAthletesAthleteIdCyclesRouteWithChildren,
    CoachAthletesAthleteIdEnduranceRoute: CoachAthletesAthleteIdEnduranceRoute,
    CoachAthletesAthleteIdStatsRoute: CoachAthletesAthleteIdStatsRoute,
  }

const CoachAthletesAthleteIdRouteWithChildren =
  CoachAthletesAthleteIdRoute._addFileChildren(
    CoachAthletesAthleteIdRouteChildren,
  )

interface CoachRouteChildren {
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachInvitesRoute: typeof CoachInvitesRoute
  CoachMeRoute: typeof CoachMeRoute
  CoachMethodologyRoute: typeof CoachMethodologyRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAthletesAthleteIdRoute: typeof CoachAthletesAthleteIdRouteWithChildren
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachExercisesRoute: CoachExercisesRoute,
  CoachInvitesRoute: CoachInvitesRoute,
  CoachMeRoute: CoachMeRoute,
  CoachMethodologyRoute: CoachMethodologyRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachAthletesAthleteIdRoute: CoachAthletesAthleteIdRouteWithChildren,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface PatientRouteChildren {
  PatientCalendarRoute: typeof PatientCalendarRoute
  PatientMeRoute: typeof PatientMeRoute
  PatientProgressionRoute: typeof PatientProgressionRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientSessionsSessionIdRoute: typeof PatientSessionsSessionIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientCalendarRoute: PatientCalendarRoute,
  PatientMeRoute: PatientMeRoute,
  PatientProgressionRoute: PatientProgressionRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientSessionsSessionIdRoute: PatientSessionsSessionIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PhysioTemplatesRouteChildren {
  PhysioTemplatesTemplateIdRoute: typeof PhysioTemplatesTemplateIdRoute
}

const PhysioTemplatesRouteChildren: PhysioTemplatesRouteChildren = {
  PhysioTemplatesTemplateIdRoute: PhysioTemplatesTemplateIdRoute,
}

const PhysioTemplatesRouteWithChildren = PhysioTemplatesRoute._addFileChildren(
  PhysioTemplatesRouteChildren,
)

interface PhysioPatientsPatientIdRouteChildren {
  PhysioPatientsPatientIdCalendarRoute: typeof PhysioPatientsPatientIdCalendarRoute
  PhysioPatientsPatientIdProgressionRoute: typeof PhysioPatientsPatientIdProgressionRoute
  PhysioPatientsPatientIdPlansPlanIdRoute: typeof PhysioPatientsPatientIdPlansPlanIdRoute
  PhysioPatientsPatientIdSessionsSessionIdRoute: typeof PhysioPatientsPatientIdSessionsSessionIdRoute
}

const PhysioPatientsPatientIdRouteChildren: PhysioPatientsPatientIdRouteChildren =
  {
    PhysioPatientsPatientIdCalendarRoute: PhysioPatientsPatientIdCalendarRoute,
    PhysioPatientsPatientIdProgressionRoute:
      PhysioPatientsPatientIdProgressionRoute,
    PhysioPatientsPatientIdPlansPlanIdRoute:
      PhysioPatientsPatientIdPlansPlanIdRoute,
    PhysioPatientsPatientIdSessionsSessionIdRoute:
      PhysioPatientsPatientIdSessionsSessionIdRoute,
  }

const PhysioPatientsPatientIdRouteWithChildren =
  PhysioPatientsPatientIdRoute._addFileChildren(
    PhysioPatientsPatientIdRouteChildren,
  )

interface PhysioRouteChildren {
  PhysioBandsRoute: typeof PhysioBandsRoute
  PhysioInvitesRoute: typeof PhysioInvitesRoute
  PhysioMeRoute: typeof PhysioMeRoute
  PhysioTemplatesRoute: typeof PhysioTemplatesRouteWithChildren
  PhysioIndexRoute: typeof PhysioIndexRoute
  PhysioPatientsPatientIdRoute: typeof PhysioPatientsPatientIdRouteWithChildren
}

const PhysioRouteChildren: PhysioRouteChildren = {
  PhysioBandsRoute: PhysioBandsRoute,
  PhysioInvitesRoute: PhysioInvitesRoute,
  PhysioMeRoute: PhysioMeRoute,
  PhysioTemplatesRoute: PhysioTemplatesRouteWithChildren,
  PhysioIndexRoute: PhysioIndexRoute,
  PhysioPatientsPatientIdRoute: PhysioPatientsPatientIdRouteWithChildren,
}

const PhysioRouteWithChildren =
  PhysioRoute._addFileChildren(PhysioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  PatientRoute: PatientRouteWithChildren,
  PhysioRoute: PhysioRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
